# Generated by Django 3.2.7 on 2021-09-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logintrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintrial',
            name='try_at',
            field=models.DateTimeField(),
        ),
    ]
